#!/bin/bash

TARGET="$1"
case "$TARGET" in
    tbird | tb | thunderbird)
        TARGET=tbird
        DEF=MOZ_THUNDERBIRD
        ;;
    suite | sm | seamonkey)
        TARGET=suite
        DEF=MOZ_SEAMONKEY
        ;;
    *)
	echo "please specify either tbird or suite"
	exit 1
	;;
esac

VERSION="0.7.3"
BUILDDIR="build-$TARGET"
XPINAME="bidimailui_${TARGET}.xpi"
BUILDTOOLSDIR="../buildtools"
export PERL5LIB="`pwd`/$BUILDTOOLSDIR"


rm -rf $BUILDDIR
mkdir $BUILDDIR

$BUILDTOOLSDIR/preprocessor.pl -D$DEF jar.mn > $BUILDDIR/jar.mn
$BUILDTOOLSDIR/make-jars.pl -v -z zip -p "$BUILDTOOLSDIR/preprocessor.pl -D$DEF -DVERSION=$VERSION"  -s . -d . < $BUILDDIR/jar.mn || exit
echo -e "\nJAR files ready\n"
$BUILDTOOLSDIR/preprocessor.pl -D$DEF "-DVERSION=$VERSION" install.rdf > $BUILDDIR/install.rdf
rm -rf bidimailpack
rm -rf bidimailpack-mac-skin
rm -f installed-chrome.txt

mkdir $BUILDDIR/defaults
mkdir $BUILDDIR/defaults/preferences
cp defaults/preferences/bidimailui.js $BUILDDIR/defaults/preferences
mkdir $BUILDDIR/chrome
mv bidimailpack.jar $BUILDDIR/chrome/bidimailpack.jar

case "$TARGET" in
    tbird)
        mkdir $BUILDDIR/platform/
        mkdir $BUILDDIR/platform/Darwin
        mkdir $BUILDDIR/platform/Darwin/chrome
        mv bidimailpack-mac-skin.jar $BUILDDIR/platform/Darwin/chrome
        cp chrome.manifest $BUILDDIR/
        cp platform/Darwin/chrome.manifest $BUILDDIR/platform/Darwin/chrome.manifest
        cd $BUILDDIR
	zip -r $XPINAME  \
	  chrome/bidimailpack.jar \
	  defaults/ \
	  platform/Darwin/chrome.manifest \
	  platform/Darwin/chrome/bidimailpack-mac-skin.jar \
	  install.rdf \
	  chrome.manifest || exit
        ;;
    suite)
        $BUILDTOOLSDIR/preprocessor.pl -D$DEF "-DVERSION=$VERSION" install.js > $BUILDDIR/install.js
        cd $BUILDDIR
	zip -r $XPINAME  \
	  chrome/bidimailpack.jar \
	  defaults/ \
	  install.rdf \
	  install.js || exit
        ;;
esac

echo -e "\nXPI ready\n"
