#!/bin/bash

TARGET="$1"
case "$TARGET" in
    tbird | tb | thunderbird)
        TARGET=tbird
        DEFS="-DMOZ_THUNDERBIRD"
        ;;
    suite | sm | seamonkey)
        TARGET=suite
        DEFS="-DMOZ_SEAMONKEY"
        ;;
    *)
	echo "please specify either tbird or suite"
	exit 1
	;;
esac

shift 1

if [ -n "$1" ]; then
	DEFS+=" -DDEBUG"
	while [ -n "$1" ]; do
		DEFS="$DEFS -DDEBUG_$1"
		shift 1
	done
fi

VERSION="0.8"
DEFS="$DEFS -DVERSION=$VERSION"
echo -e "Building the XPI with the following definitions:\n\n$DEFS\n"
BUILDDIR="build-$TARGET"
XPINAME="bidimailui_${TARGET}.xpi"
BUILDTOOLSDIR="../buildtools"
export PERL5LIB="`pwd`/$BUILDTOOLSDIR"

rm -rf $BUILDDIR
mkdir $BUILDDIR

$BUILDTOOLSDIR/preprocessor.pl $DEFS jar.mn > $BUILDDIR/jar.mn
$BUILDTOOLSDIR/make-jars.pl -v -z zip -p "$BUILDTOOLSDIR/preprocessor.pl $DEFS"  -s . -d . < $BUILDDIR/jar.mn || exit
echo -e "\nJAR files ready\n"
$BUILDTOOLSDIR/preprocessor.pl $DEFS install.rdf > $BUILDDIR/install.rdf
rm -rf bidimailpack
rm -rf bidimailpack-mac-skin
rm -f installed-chrome.txt

mkdir $BUILDDIR/defaults
mkdir $BUILDDIR/defaults/preferences
cp defaults/preferences/bidimailui.js $BUILDDIR/defaults/preferences
mkdir $BUILDDIR/chrome
mv bidimailpack.jar $BUILDDIR/chrome/bidimailpack.jar

case "$TARGET" in
    tbird)
        mkdir $BUILDDIR/platform/
        mkdir $BUILDDIR/platform/Darwin
        mkdir $BUILDDIR/platform/Darwin/chrome
        mv bidimailpack-mac-skin.jar $BUILDDIR/platform/Darwin/chrome
        cp chrome.manifest $BUILDDIR/
        cp platform/Darwin/chrome.manifest $BUILDDIR/platform/Darwin/chrome.manifest
        cd $BUILDDIR
	zip -r $XPINAME  \
	  chrome/bidimailpack.jar \
	  defaults/ \
	  platform/Darwin/chrome.manifest \
	  platform/Darwin/chrome/bidimailpack-mac-skin.jar \
	  install.rdf \
	  chrome.manifest || exit
        ;;
    suite)
        $BUILDTOOLSDIR/preprocessor.pl $DEFS install.js > $BUILDDIR/install.js
        cd $BUILDDIR
	zip -r $XPINAME  \
	  chrome/bidimailpack.jar \
	  defaults/ \
	  install.rdf \
	  install.js || exit
        ;;
esac

echo -e "\nXPI ready\n"
