#!/bin/bash

SHORTNAME="bidimailui"
VERSION="0.11"
TARGET="$1"
BETA_SUBVERSION="1"
UUID="{54e72d7b-ed31-4736-854f-f517358f21ee}"

PREPROCESSOR_PARAMS+=" -DUUID=$UUID -DSHORTNAME=$SHORTNAME"

case "$TARGET" in
	tbird | tb | thunderbird)
		TARGET=tbird
		PREPROCESSOR_PARAMS+=" -DMOZ_THUNDERBIRD"
		;;
		echo "Please specify thunderbird as the target (yes, that's a bit redundant)."
	exit 1
	;;
esac

if [ -z "$EXTENSION_RELEASE" ]; then
	VERSION="${VERSION}b${BETA_SUBVERSION}"
	PREPROCESSOR_PARAMS+=" -DIS_BETA_BUILD"
fi
PREPROCESSOR_PARAMS+=" -DVERSION=$VERSION"

shift 1

# all arguments after the target app are #define 'd in the XUL preprocessor,
# with a DEBUG_ prefix; so if you want to, say, have debugging code specific
# to the function myFancyFunc(), write it like so:
#
#   #ifdef DEBUG_myFancyFunc 
#     debugging code etc. etc.
#   #endif
#
# then invoke
#
#   dobuild tbird myFancyFunc
#
# to have your debugging code enabled

if [ -n "$1" ]; then
	PREPROCESSOR_PARAMS+=" -DDEBUG"
	while [ -n "$1" ]; do
		PREPROCESSOR_PARAMS="$PREPROCESSOR_PARAMS -DDEBUG_$1"
		shift 1
	done
else
	PREPROCESSOR_PARAMS+=" --no-line-comments"
fi

BUILDDIR="build/$TARGET"
XPINAME="${SHORTNAME}_${VERSION}_${TARGET}.xpi"
LINKNAME="${SHORTNAME}_${TARGET}.xpi"
BUILDTOOLSDIR="../buildtools"
export PERL5LIB="`pwd`/$BUILDTOOLSDIR"

# TODO: split builddir by /'s and try to create everything along the path
if [ ! -d build ] ; then mkdir build; fi
if [ ! -d $BUILDDIR ] ; then mkdir $BUILDDIR; else rm -rf $BUILDDIR/*; fi

$BUILDTOOLSDIR/preprocessor.pl $PREPROCESSOR_PARAMS jar.mn > $BUILDDIR/jar.mn
# Our invocation of make-jars.pl doesn't literally make JAR files, it only preprocesses and copies.
$BUILDTOOLSDIR/make-jars.pl -q -f flat -z zip -p "$BUILDTOOLSDIR/preprocessor.pl $PREPROCESSOR_PARAMS"  -s . -d . < $BUILDDIR/jar.mn || exit
$BUILDTOOLSDIR/preprocessor.pl $PREPROCESSOR_PARAMS install.rdf > $BUILDDIR/install.rdf # For pre-68 Thunderbird versions
$BUILDTOOLSDIR/preprocessor.pl $PREPROCESSOR_PARAMS manifest.json > $BUILDDIR/manifest.json # For Thunderbird 68 and later
rm -f installed-chrome.txt

mkdir -p $BUILDDIR/defaults/preferences
cp defaults/preferences/${SHORTNAME}.js $BUILDDIR/defaults/preferences
mv ${SHORTNAME} $BUILDDIR/chrome

case "$TARGET" in
	tbird)
		mkdir -p $BUILDDIR/platform/Darwin
		mv ${SHORTNAME}-mac-skin $BUILDDIR/platform/Darwin/chrome
		$BUILDTOOLSDIR/preprocessor.pl $PREPROCESSOR_PARAMS chrome.manifest > $BUILDDIR/chrome.manifest
		cp platform/Darwin/chrome.manifest $BUILDDIR/platform/Darwin/chrome.manifest
		cd $BUILDDIR
	zip -r $XPINAME  \
		chrome \
		defaults/ \
		platform/Darwin/chrome.manifest \
		platform/Darwin/chrome \
		install.rdf \
		manifest.json \
		chrome.manifest || exit
		;;
esac

ln $XPINAME $LINKNAME
